### ISSUE TITLE
Enhancement Request: Show Axis Coordinates

### ISSUE THREAD

**Issue by jkulesza** [markummitchell/engauge-digitizer#355] opened 2019-09-21 01:55 UTC
It would be helpful to have a status bar / dialog box / etc. display of the three points used to define an axis to ensure that the program has recorded them correctly based on user entry.  

For example, I was working with a curve recently that required very small values in scientific notation that were failing to define the axes.  It's not clear what values the program thought I was using/entering.

**Comment by jkulesza** [comment] 2019-09-22 14:55
For example, using Engauge Digitizer 12.1 on macOS 10.14.6 with these three points fails:

(1,1e-22), (1,1e-25), and (100, 1e-25)

when the third point is entered with the message:

<img width="532" alt="Screen Shot 2019-09-22 at 8 54 31 AM" src="https://user-images.githubusercontent.com/9939059/65389727-9debb500-dd16-11e9-9926-c543da5bf208.png">

It is not clear what coordinates it thinks I'm using, but I would expect these to work.

**Comment by markummitchell** [comment] 2019-09-23 05:56
I did some investigation. The Qt library, on which Engauge runs, is not happy with the 27 orders of magnitude in the coordinates. Specifically, the 3x3 matrix used to convert between screen and graph coordinates uses (x0,y0,1) as the first column, (x1,y1,1) as the second column and (x2,y2,1) as the third column. To determine if the matrix is invertible, the determinant's value of 9.9e-21 is compared in qglobal.h to 0.000000000001. Although this is where the problem currently manifests, I am sure that somehow getting past that point by upgrading the code would immediately cause other problems elsewhere in the code. Although all the issues could be fixed, this would result in a huge amount of work. As a point of reference, it took months to get log scale working well.

An immediate fix is to manually rescale your data - like maybe adding 20 to each exponent in the y coordinate. Would that work for you? Maybe using log scale?

In any case, before closing this issue I would like to, at least, improve the error message to explain when the issue is a huge dynamic range in the coordinate values.

**Comment by jkulesza** [comment] 2019-09-24 06:10
> I did some investigation. The Qt library, on which Engauge runs, is not happy with the 27 orders of magnitude in the coordinates. Specifically, the 3x3 matrix used to convert between screen and graph coordinates uses (x0,y0,1) as the first column, (x1,y1,1) as the second column and (x2,y2,1) as the third column. To determine if the matrix is invertible, the determinant's value of 9.9e-21 is compared in qglobal.h to 0.000000000001. Although this is where the problem currently manifests, I am sure that somehow getting past that point by upgrading the code would immediately cause other problems elsewhere in the code. 

That makes sense.  Besides, would newer versions of Qt even have a different, useful, criterion?  The one cited is 1e-12 (if I counted correctly).  Machine precision is ~1e-15, which wouldn't cover the 1e-20 calculated for the determinant.

> Although all the issues could be fixed, this would result in a huge amount of work. As a point of reference, it took months to get log scale working well.  An immediate fix is to manually rescale your data - like maybe adding 20 to each exponent in the y coordinate. Would that work for you? Maybe using log scale?

Taking this approach, I'd rather seen Engauge do the rescaling internally.  I've nominally already indicated that my axes are log-scaled.  So, the software should be able to take the plot coordinates, transform to log coordinates, do everything else it needs, and then untransform back to graph coordinates when I request output.  Thoughts?

> In any case, before closing this issue I would like to, at least, improve the error message to explain when the issue is a huge dynamic range in the coordinate values.

Sounds good, thanks.  It wasn't really clear what I was supposed to take from that.  Do you think the original request also has merit (to echo the entered coordinates somewhere)?  For a while, it seemed like it wasn't accepting scientific notation and I had know way to confirm this.

**Comment by markummitchell** [comment] 2019-10-01 06:01
The initial problem is probably fixed. There is at least one issue later so more work needs to be done.

**Comment by jkulesza** [comment] 2019-10-02 05:42
> The initial problem is probably fixed. There is at least one issue later so more work needs to be done.

Awesome, thanks!  You provided some *amazing* support yet again.  I look forward to trying this in the next release.

**Comment by markummitchell** [comment] 2019-11-30 02:35
Testing shows things are working fine.

**Closed by markummitchell** 2019-11-30 02:35 UTC
Labels: enhancement

**Comment by jkulesza** [comment] 2019-11-30 15:52
I just tested 12.1 on my curve.  Thanks for your work; it creates the coordinates and digitizes correctly now.  Thanks again!
