### ISSUE TITLE
Version 10.4 on Windows 7 - slow responses

### ISSUE THREAD

**Issue by mingweii** [markummitchell/engauge-digitizer#250] opened 2017-11-20 23:08 UTC
Hi,

I installed version 10.4 on my virtual box machine of Windows 7, where I allocated video memory 128mb and RAM 3GB. When I tried to add points on an image, it would take about 10 seconds to respond for each of point added. And if I clicked it too many times in a row, it would not respond for about 30 seconds to respond the new points.

However, I also have a portable version 4.1 that doesn't have the same problem.

Thanks!

**Comment by markummitchell** [comment] 2017-11-24 02:21
Can you attach your file? I have tried in a virtual machine with 3GB, single CPU and 32MB, and saw fast performance. Also, I do not understand 'portable version 4.1'. Is that the operating system?

**Comment by markummitchell** [comment] 2017-11-24 02:34
Also, were you using encryption of the hard drive in the guest and/or host operating systems?

**Comment by mingweii** [comment] 2017-11-24 02:47
Version 4.1 is the older version of engauge digitalizor I have used for a while, which is not on the github before. I put the file here:
 [https://drive.google.com/file/d/1em57T753qMOrMCY1KMmtF0Yop3Q_PPnj/view?usp=sharing](url)

My hard drive is not encrypted. The windows 7 64-bit I used on the VirtualBox was just installed for my personal use that only one user is available.

Thanks!

**Comment by markummitchell** [comment] 2017-12-14 07:54
This seems to be a very uncommon issue. I believe the issue is specific to your computer so I am closing this issue.

**Closed by markummitchell** 2017-12-14 07:54 UTC
Labels: wontfix
