### ISSUE TITLE
possible bug in Version 12

### ISSUE THREAD

**Issue by BobRodd** [markummitchell/engauge-digitizer#392] opened 2020-10-11 16:30 UTC
I have recently done a major update from Version 4 to Version 12.1 and discovered 2 possible bugs.  I am running Windows 10 Build 19041.508.

When I start Enguage it comes up full screen mode but is offset to the right so that the vertical scroll bar is not visible and neither of the dash, box, and X that should be at the top right hand of the box.  The problem is that the box is locked into that position and can't be moved.

If I have multiple sets of curves on a single plot I have discovered that after I digitize the three coordinate points on the plot, save the .dig file, digitize the first set of curves, export them, and then close the program there is no way to scroll the plot vertically after I restart Enguage.  This problem occurs since the help screen with check boxes no longer appears on the right part of the screen moving the vertical scroll bar to the left and back onto the screen.

I do very much like what appears to be a much improved method of selecting whole sections of a curve without selecting separate points.

VBR
Bob

**Comment by BobRodd** [comment] 2020-10-11 19:11
Update on the previous comment.  shortly after I sent the previous post I opened Enguage and just left it sitting for about a half and hour.  Surprisingly, after the long sit, I was not only able to move the application window, I was able to resize it.  Then to test this change I turned off my computer for about 2 hours, restarted it, and opened up Enguage.  The changes I made were still there and now thing work correctly.

Sorry about the false alarm but I had the problem mentioned over a number of usages of the program.

Bob

**Comment by markummitchell** [comment] 2020-10-25 20:17
In a build older than your build 19041.508, and a build newer than 19.041.508, I tried (1) maximizing (2) closing (3) reopening. In multiple tries the new window was always maximized correctly. You might consider starting Windows 10 in Safe Mode to see if there is another application that is causing the problem. Or you might have a monitor that is bleeding offscreen - you can try different screen resolutions to see if any work.

I have tested with normal resolutions like 1920x1080 and 3840x2160.

**Comment by markummitchell** [comment] 2020-10-25 20:32
Has the font or screen scaling been changed from 100%?

**Comment by BobRodd** [comment] 2020-10-26 00:42
After I imported the data I did zoom in while doing the actual digitizing.  I don’t think I zoomed back out before I exited the program and got the message about saving the project.  If you feel that is the problem I will simply save the project as soon as I import the data in the future.
 
Thank you for giving me a clue.
 
Stay safe and healthy;
Bob

**Comment by markummitchell** [comment] 2020-10-28 02:31
By any chance do you know your screen resolution, and also your graphics driver (NVIDIA, Intel..)?

I tried with Engauge zoom in various settings and it worked. So I could not recreate the problem.

If you have used Windows 'scaling' for the Display then I would bet it is Windows. I

**Comment by BobRodd** [comment] 2020-10-28 12:27
See Below.  It sounds like the best thing for me to do is to uninstall and re-install the program on my system.  It certainly seems that if can’t reproduce the problem it is just something unique to my system and NOT a bug at all.

**Comment by markummitchell** [comment] 2020-10-28 13:45
First the bad news:

I just tried your 1680x1050 resolution with Nvidia turned off so I was using the Intel HD driver. I did see the window appear to the right of the expected location, although not far enough to obscure the window buttons. The system font was so ungainly huge that I suspect that resolution is not well supported, and that could be the source of your problems. Specifically, my system font looks great at 1920x1024 and 3840x2048 even though those two resolutions are very different, but the system font was broken at 1680x1050 even though that is close to 1920x1024.

The problem does not appear to be in my Engauge code, which I can fix. Part of the problem may be in the Qt libraries my code uses, but I cannot fix those. Part of the problem is definitely in the operating system and its drivers, which I also cannot fix.

The good news:

You should be able to regain control of Engauge using the standard WindowsKey + UpArrow. That will maximize the application and make the dialog controls accessible.

Another option is to not save in Full Screen mode.

Another option is to add the command line parameter '-reset' so you run engauge as 'engauge.exe -reset'. This will reset ALL settings so the window position is lost, as well as many other useful settings you might need.

Another option is to run in Linux using dual boot, another computer, or a virtual machine.

**Comment by BobRodd** [comment] 2020-10-28 14:01
Thanks for both the good news and the bad news.  Both are VERY helpful.
 
Thanks again;
Bob

**Closed** 2020-10-29 07:46 UTC
Labels: question
