### ISSUE TITLE
Weird curve in dig file produces crash on export

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge-digitizer#78] opened 2016-02-25 18:14 UTC
Image file taken from https://github.com/markummitchell/engauge6/issues/75

I've run Segment fill and created weird curve on purpose. Export leads to crash of Engauge.
[PNextGenTFwebFig3.zip](https://github.com/markummitchell/engauge6/files/147073/PNextGenTFwebFig3.zip)

**Comment by markummitchell** [comment] 2016-02-26 05:33
The DIG file has 0 values for the ordinal values in the first few points. This is a serious problem in that the ordinal values were not correct before the file was saved. I will try to recreate the problem so I can fix it.

**Comment by np-8** [comment] 2016-02-26 08:43
I managed to crash Engauge with [this](http://www.tvu.com/PNextGenTFwebFig3.jpg) figure by this steps.

1) Enter the y-axis points as (0,2; 0) and (0,2; 10). This is accepted, but engauge turns that into (0,0) and (0, 10) without a warning.

2) Change the x-axis from cartesian to log

3) Save.

Also, the coordinates looked weird:
![engaugenan](https://cloud.githubusercontent.com/assets/17479683/13347322/ac51517c-dc75-11e5-99ff-7d32fcc29ee4.PNG)

**Comment by markummitchell** [comment] 2016-03-04 06:53
I cannot reproduce the problem with the duplicate ordinals, which may be fixed by the cbc03a7 commit. That fix probably solved multiple issues even if it does not help with this issue. If the problem reappears, it would be nice to know the general steps that were followed when the file was created. Were any curves renamed? Were any points dragged or cut? Were undo and/or redo used?

The secondary issue with the log coordinates not working with Finnish locale is probably fixed.

**Closed** 2016-03-07 06:11 UTC
Labels: bug
