### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by k1moradi** [markummitchell/engauge-digitizer#322] opened 2019-04-27 23:31 UTC
Hi. Engauge uses 100% of one of the cores all the time, without being used.

**Comment by markummitchell** [comment] 2019-04-29 05:53
What operating system are you using, and which release (flatpak, snap, ...)? Also, it would be helpful to know what was happening before the CPU usage grew. If the problem repeats, it may be good to enter Control+Shift+E to generate an error_report.xml file that I can use to identify the problem.

**Comment by k1moradi** [comment] 2019-04-29 17:52
I use the latest version on windows 10 64 bit (without installer).
It happened after successfully exporting CSV values. It happened several times the other night but I could not reproduce the error today. I will send you the report XML as soon as I could reproduce the error.

**Comment by markummitchell** [comment] 2019-05-01 04:42
This is a duplicate of #323

**Closed by markummitchell** 2019-05-01 04:42 UTC
