### ISSUE TITLE
Export to CSV has problems

### ISSUE THREAD

**Issue by hdrz** [markummitchell/engauge-digitizer#399] opened 2021-02-28 14:21 UTC
I have this file where I digitize few lines from log-log plot, each line is only two points. Viewing inside engauge shows the correct x-y values.
When exporting to CSV the values are different, it is visible also in the settings>export dialog.

engauge v12.1

[test.zip](https://github.com/markummitchell/engauge-digitizer/files/6056916/test.zip)

**Comment by jhossbach** [comment] 2021-05-20 10:02
I can confirm this issue, I have a linear plot, engauge also shows the correct x-y-values that get changed during export to either CSV or TSV.
Also using engauge v12.1, this is my testfile: 
[phase.zip](https://github.com/markummitchell/engauge-digitizer/files/6514916/phase.zip)

**Comment by thorade** [comment] 2021-06-30 13:20
Ran into the same issue today. Was this working in previous releases? I am happy to use an older release as temporary workaround.

**Comment by markummitchell** [comment] 2021-07-03 16:41
Looks like a log coordinate fix for smoothing caused problems in version 12. Fixed in version 13 which will be released soon since this is important.

**Closed by markummitchell** 2021-07-03 16:41 UTC
Labels: bug
